[package]
name = "beermate-webservice"
version = "0.1.0"
authors = ["Thomas Schedler <thomas@chirimoya.at>"]

[dependencies]
iron = "*"
router = "*"
websocket = "0.17.*"
rustc-serialize = "0.3.*"
deque = "0.3.*"
rand = "0.3.*"
